name: wireguard-ammp
version: '1.0.20200513'
summary: WireGuard VPN (userspace)
description: |
  WireGuard® is an extremely simple yet fast and modern VPN that utilizes state-of-the-art cryptography. It aims to be faster, simpler, leaner, and more useful than IPSec, while avoiding the massive headache. It intends to be considerably more performant than OpenVPN.
  This snap packages the wireguard-go userspace executable (https://git.zx2c4.com/wireguard-go/about/) and the wg and wg-quick binaries built from the main repo (https://git.zx2c4.com/WireGuard/about/).
  
  With an overlay, /etc/wireguard is mapped to $SNAP_COMMON (conventionally /var/snap/wireguard-ammp/common) - so this is where you should put configuration files such as wg0.conf.
  Once the wg0.conf config file is in place and you've connected the network-control and firewall-control interaces, run
  ```
  sudo wireguard-ammp.wg-quick up wg0
  ```
  to bring up the interface.
  
  You may get an error `Unable to modify interface: Protocol not supported` due to a bug in some versions of snapd - see https://forum.snapcraft.io/t/raspberry-pi-3-ubuntu-core-18-network-control-interface-issue/14773/7 for a workaround.

grade: stable
confinement: strict

base: core18

apps:
  wg:
    command: wg
    plugs: [network, network-control, network-bind, firewall-control]
    environment:
      WG_SOCKET_DIR: $SNAP_DATA/socket
  wg-quick:
    command: wg-quick
    plugs: [network, network-control, network-bind, firewall-control]
    environment:
      WG_SOCKET_DIR: $SNAP_DATA/socket
      # WG_I_PREFER_BUGGY_USERSPACE_TO_POLISHED_KMOD: 1
  wireguard-go:
    command: wireguard-go
    plugs: [network, network-control, network-bind, firewall-control]
    environment:
      WG_SOCKET_DIR: $SNAP_DATA/socket
      # WG_I_PREFER_BUGGY_USERSPACE_TO_POLISHED_KMOD: 1

parts:
  wireguard:
    plugin: make
    source-type: git
    source: https://git.zx2c4.com/wireguard-tools
    source-tag: v1.0.20200513
    source-subdir: src/
    build-packages:
      - libmnl-dev
      - build-essential
    override-pull: |
      snapcraftctl pull
      patch -p1 < $SNAPCRAFT_PROJECT_DIR/tools.patch
    stage-packages:
      - libc6
      - libmnl0
      - resolvconf
    make-parameters: [WITH_WGQUICK=yes]
  wireguard-go:
    plugin: make
    source-type: git
    source: git://git.zx2c4.com/wireguard-go
    source-branch: v0.0.20200320
    override-pull: |
      snapcraftctl pull
      patch -p1 < $SNAPCRAFT_PROJECT_DIR/svet.patch
    build-snaps: [go]

layout:
  /etc/wireguard:
    bind: $SNAP_COMMON
