name: wireguard-ammp
version: '0.0.20200121'
summary: WireGuard VPN (userspace)
description: |
  WireGuard® is an extremely simple yet fast and modern VPN that utilizes state-of-the-art cryptography. It aims to be faster, simpler, leaner, and more useful than IPSec, while avoiding the massive headache. It intends to be considerably more performant than OpenVPN.
  This snap packages the wireguard-go userspace executable (https://git.zx2c4.com/wireguard-go/about/) and the wg and wg-quick binaries built from the main repo (https://git.zx2c4.com/WireGuard/about/).
  
  With an overlay, /etc/wireguard is mapped to $SNAP_COMMON - so that's where WireGuard will look for configuration and key files.

grade: stable
confinement: strict

base: core18

architectures:
  - build-on: amd64
  - build-on: armhf

apps:
  wg:
    command: wg
    plugs: [network, network-control, network-bind, firewall-control]
    environment:
      WG_SOCKET_DIR: $SNAP_DATA/socket
  wg-quick:
    command: wg-quick
    plugs: [network, network-control, network-bind, firewall-control]
    environment:
#      WG_I_PREFER_BUGGY_USERSPACE_TO_POLISHED_KMOD: 1
      WG_SOCKET_DIR: $SNAP_DATA/socket
  wireguard-go:
    command: wireguard-go
    plugs: [network, network-control, network-bind, firewall-control]
    environment:
#      WG_I_PREFER_BUGGY_USERSPACE_TO_POLISHED_KMOD: 1
      WG_SOCKET_DIR: $SNAP_DATA/socket

parts:
  wireguard:
    plugin: make
    source-type: git
    source: https://git.zx2c4.com/wireguard-tools
    source-tag: v1.0.20200121
    source-subdir: src/
    build-packages:
      - libmnl-dev
      - build-essential
    override-pull: |
      snapcraftctl pull
      patch -p1 < $SNAPCRAFT_PROJECT_DIR/tools.patch
    stage-packages:
      - libc6
      - libmnl0
      - resolvconf
    make-parameters: [WITH_WGQUICK=yes]
  wireguard-go:
    plugin: make
    source-type: git
    source: git://git.zx2c4.com/wireguard-go
    source-branch: v0.0.20200121
    override-pull: |
      snapcraftctl pull
      patch -p1 < $SNAPCRAFT_PROJECT_DIR/svet.patch
    build-snaps: [go]

passthrough:
  layout:
    /etc/wireguard:
      bind: $SNAP_COMMON
